version: "3.8"

services:
  vue-landing:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"  # Відкриваємо порт 8080 для HTTP
      - "443:443"  # Відкриваємо порт 8443 для HTTPS
    container_name: vue-landing
